[project]
name = "spotifylyricstreamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dylan Fritz", email = "dfritz1211@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "spotipy>=2.26.0",
    "syncedlyrics>=1.0.1",
]

[project.scripts]
spotifylyricstreamer = "spotifylyricstreamer:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
